language: cpp
matrix:
    include:
        os: linux
        dist: trusty
        sudo: required
        addons:
            apt:
                packages:
                    - libsfml-dev
                    - care



        script:
            - mkdir build
            - cmake .
            - cmake --build .
            - care -o AppDir/ bin/ariel
            - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
            - chmod a+x linuxdeployqt-continuous-x86_64.AppImage