language: cpp
matrix:
    include:
        os: linux
        dist: xenial
        sudo: required
        addons:
            apt:
                packages:
                    - libsfml-dev
                    - libsfml-graphics2*
                    - proot
                    - freeglut3-dev
                    - libxmu-dev
                    - libxi-dev

        script:
            - cd gen/
            - ./AppImage.sh
            - cd ..
            - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
            - chmod a+x linuxdeployqt-continuous-x86_64.AppImage

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Ariel_Engine-x86_64.AppImage
  skip_cleanup: true
  on:
    repo: https://github.com/MIfeanyi/ariel
    tags: true
