language: cpp
matrix:
    include:
        os: linux
        dist: trusty
        sudo: required
        addons:
            apt:
                packages:
                    - libsfml-dev



        script:
            - mkdir build
            - cmake .
            - make