language: cpp
matrix:
    include:
        os: linux
        dist: trusty
        sudo: required
        addons:
            apt:
                packages:
                    - libsfml-dev
                    - proot

        script:
            - ./gen/AppImage.sh
            - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
            - chmod a+x linuxdeployqt-continuous-x86_64.AppImage

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Ariel_Engine-x86_64.AppImage
  skip_cleanup: true
  on:
    repo: https://github.com/MIfeanyi/ariel
    tags: true
