language: cpp
matrix:
    include:
        os: linux
        dist: xenial
        sudo: required
        addons:
            apt:
                packages:
                    - libsfml-dev
                    - proot
                    - freeglut3-dev
                    - libxmu-dev
                    - libxi-dev
        before_install:
            - sudo apt-get -qq update
            - sudo apt-get install libsfml-dev freeglut3-dev libxmu-dev libxi-dev -y

        script:
            - cd gen/
            - ./AppImage.sh

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Ariel_Engine-x86_64.AppImage
  skip_cleanup: true
  on:
    repo: https://github.com/MIfeanyi/ariel.git
    tags: true
